---
- name: deploy ha config file
  copy:
    src: configuration.yaml
    dest: /home/ha/.homeassistant/configuration.yaml
    owner: ha
    group: ha
  become: true

- name: deploy ha Automations file
  copy:
    src: automations.yaml
    dest: /home/ha/.homeassistant/automations.yaml
    owner: ha
    group: ha
  become: true

- name: deploy ha Groups file
  copy:
    src: groups.yaml
    dest: /home/ha/.homeassistant/groups.yaml
    owner: ha
    group: ha
  become: true

- name: deploy ha Secrets file
  copy:
    src: secrets.yaml
    dest: /home/ha/.homeassistant/secrets.yaml
    owner: ha
    group: ha
  become: true

- name: restart the HA service
  systemd:
    name: home-assistant@ha.service
    state: restarted
  become: true

- name: deploy zigbee2mqtt config file
  copy:
    src: zigbee2mqtt.config.yaml
    dest: /opt/zigbee2mqtt/data/configuration.yaml
    owner: ha
    group: ha
  become: true

- name: restart the zigbee2mqtt service
  systemd:
    name: zigbee2mqtt.service
    state: restarted
  become: true